version: '3.7'

services:
  web:
    build: .
    ports:
      - "5310:5310"
    env_file:
      - .env
    volumes:
      - .:/workspace
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  dramatiq:
    build: .
    command: dramatiq task_proxy
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/workspace
    deploy:
      resources:
        limits:
          cpus: "0.8"