version: '3.7'

services:
  web:
    build: .
    ports:
      - "5310:5310"
    env_file:
      - .env
    volumes:
      - .:/workspace
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  rq-worker:
    build: .
    command: rq worker
    depends_on:
      - redis
    volumes:
      - .:/workspace