services:
  web:
    build: .
    ports:
      - "5310:5310"
    env_file:
      - .env
    volumes:
      - .:/workspace
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  dramatiq:
    build: .
#    command: dramatiq --threads=1 --processes=1 app.tasks
    command: dramatiq --processes=1 app.tasks
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/workspace