version: '3.7'

services:
  web:
    build: .
    ports:
      - "5310:5310"
    env_file:
      - .env
    volumes:
      - .:/workspace
    depends_on:
      - redis
    extra_hosts:
      - "bubble-killer.site:139.59.133.179"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    extra_hosts:
      - "bubble-killer.site:139.59.133.179"

  dramatiq:
    build: .
    command: dramatiq task_proxy
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/workspace
    extra_hosts:
      - "bubble-killer.site:139.59.133.179"
